run-dist:
	./build/install/app/bin/app

install:
	./gradlew clean installDist

build:
	./gradlew clean build

lint:
	./gradlew checkstyleMain

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

.PHONY: build